// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package vendorproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RequestField struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContactEmail         string   `protobuf:"bytes,4,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	ContactMobile        string   `protobuf:"bytes,5,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactPhone         string   `protobuf:"bytes,6,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	AddressStreet        string   `protobuf:"bytes,7,opt,name=addressStreet,proto3" json:"addressStreet,omitempty"`
	AddressCity          string   `protobuf:"bytes,8,opt,name=addressCity,proto3" json:"addressCity,omitempty"`
	AddressPostCode      string   `protobuf:"bytes,9,opt,name=addressPostCode,proto3" json:"addressPostCode,omitempty"`
	AddressState         string   `protobuf:"bytes,10,opt,name=addressState,proto3" json:"addressState,omitempty"`
	AddressCountry       string   `protobuf:"bytes,11,opt,name=addressCountry,proto3" json:"addressCountry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestField) Reset()         { *m = RequestField{} }
func (m *RequestField) String() string { return proto.CompactTextString(m) }
func (*RequestField) ProtoMessage()    {}
func (*RequestField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RequestField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestField.Unmarshal(m, b)
}
func (m *RequestField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestField.Marshal(b, m, deterministic)
}
func (m *RequestField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestField.Merge(m, src)
}
func (m *RequestField) XXX_Size() int {
	return xxx_messageInfo_RequestField.Size(m)
}
func (m *RequestField) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestField.DiscardUnknown(m)
}

var xxx_messageInfo_RequestField proto.InternalMessageInfo

func (m *RequestField) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RequestField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestField) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RequestField) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *RequestField) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *RequestField) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *RequestField) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *RequestField) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *RequestField) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *RequestField) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *RequestField) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

type GetRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Field                *RequestField  `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type UpdateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Field                *RequestField  `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type ActionRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ActionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BalanceRequest struct {
	Header               *RequestHeader       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *BalanceRequest_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BalanceRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BalanceRequest) GetData() *BalanceRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type BalanceRequest_Data struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest_Data) Reset()         { *m = BalanceRequest_Data{} }
func (m *BalanceRequest_Data) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest_Data) ProtoMessage()    {}
func (*BalanceRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6, 0}
}

func (m *BalanceRequest_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest_Data.Unmarshal(m, b)
}
func (m *BalanceRequest_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest_Data.Marshal(b, m, deterministic)
}
func (m *BalanceRequest_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest_Data.Merge(m, src)
}
func (m *BalanceRequest_Data) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest_Data.Size(m)
}
func (m *BalanceRequest_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest_Data proto.InternalMessageInfo

func (m *BalanceRequest_Data) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DataResponse struct {
	StatusCode           int32              `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataResponse) GetData() *DataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse_Data struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ContactEmail         string   `protobuf:"bytes,5,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	ContactMobile        string   `protobuf:"bytes,6,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactPhone         string   `protobuf:"bytes,7,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	AddressStreet        string   `protobuf:"bytes,8,opt,name=addressStreet,proto3" json:"addressStreet,omitempty"`
	AddressCity          string   `protobuf:"bytes,9,opt,name=addressCity,proto3" json:"addressCity,omitempty"`
	AddressPostCode      string   `protobuf:"bytes,10,opt,name=addressPostCode,proto3" json:"addressPostCode,omitempty"`
	AddressState         string   `protobuf:"bytes,11,opt,name=addressState,proto3" json:"addressState,omitempty"`
	AddressCountry       string   `protobuf:"bytes,12,opt,name=addressCountry,proto3" json:"addressCountry,omitempty"`
	DisplayBalanceAmount string   `protobuf:"bytes,13,opt,name=displayBalanceAmount,proto3" json:"displayBalanceAmount,omitempty"`
	BalanceAmount        float64  `protobuf:"fixed64,14,opt,name=balanceAmount,proto3" json:"balanceAmount,omitempty"`
	CreatedDate          string   `protobuf:"bytes,15,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	CreatedBy            string   `protobuf:"bytes,16,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	LastModifiedDate     string   `protobuf:"bytes,17,opt,name=lastModifiedDate,proto3" json:"lastModifiedDate,omitempty"`
	LastModifiedBy       string   `protobuf:"bytes,18,opt,name=lastModifiedBy,proto3" json:"lastModifiedBy,omitempty"`
	RecordState          string   `protobuf:"bytes,19,opt,name=recordState,proto3" json:"recordState,omitempty"`
	ReferencedBy         int64    `protobuf:"varint,20,opt,name=referencedBy,proto3" json:"referencedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse_Data) Reset()         { *m = DataResponse_Data{} }
func (m *DataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DataResponse_Data) ProtoMessage()    {}
func (*DataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7, 0}
}

func (m *DataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse_Data.Unmarshal(m, b)
}
func (m *DataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse_Data.Marshal(b, m, deterministic)
}
func (m *DataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse_Data.Merge(m, src)
}
func (m *DataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DataResponse_Data.Size(m)
}
func (m *DataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse_Data proto.InternalMessageInfo

func (m *DataResponse_Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataResponse_Data) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DataResponse_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataResponse_Data) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *DataResponse_Data) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *DataResponse_Data) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *DataResponse_Data) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *DataResponse_Data) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *DataResponse_Data) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *DataResponse_Data) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *DataResponse_Data) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *DataResponse_Data) GetDisplayBalanceAmount() string {
	if m != nil {
		return m.DisplayBalanceAmount
	}
	return ""
}

func (m *DataResponse_Data) GetBalanceAmount() float64 {
	if m != nil {
		return m.BalanceAmount
	}
	return 0
}

func (m *DataResponse_Data) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *DataResponse_Data) GetRecordState() string {
	if m != nil {
		return m.RecordState
	}
	return ""
}

func (m *DataResponse_Data) GetReferencedBy() int64 {
	if m != nil {
		return m.ReferencedBy
	}
	return 0
}

type SimpleResponse struct {
	StatusCode           int32                `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *SimpleResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SimpleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SimpleResponse) GetData() *SimpleResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleResponse_Data struct {
	DisplayBalanceAmount string   `protobuf:"bytes,1,opt,name=displayBalanceAmount,proto3" json:"displayBalanceAmount,omitempty"`
	BalanceAmount        float64  `protobuf:"fixed64,2,opt,name=balanceAmount,proto3" json:"balanceAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse_Data) Reset()         { *m = SimpleResponse_Data{} }
func (m *SimpleResponse_Data) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse_Data) ProtoMessage()    {}
func (*SimpleResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8, 0}
}

func (m *SimpleResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse_Data.Unmarshal(m, b)
}
func (m *SimpleResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse_Data.Marshal(b, m, deterministic)
}
func (m *SimpleResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse_Data.Merge(m, src)
}
func (m *SimpleResponse_Data) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse_Data.Size(m)
}
func (m *SimpleResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse_Data proto.InternalMessageInfo

func (m *SimpleResponse_Data) GetDisplayBalanceAmount() string {
	if m != nil {
		return m.DisplayBalanceAmount
	}
	return ""
}

func (m *SimpleResponse_Data) GetBalanceAmount() float64 {
	if m != nil {
		return m.BalanceAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "vendorproto.RequestHeader")
	proto.RegisterType((*RequestField)(nil), "vendorproto.RequestField")
	proto.RegisterType((*GetRequest)(nil), "vendorproto.GetRequest")
	proto.RegisterType((*CreateRequest)(nil), "vendorproto.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "vendorproto.UpdateRequest")
	proto.RegisterType((*ActionRequest)(nil), "vendorproto.ActionRequest")
	proto.RegisterType((*BalanceRequest)(nil), "vendorproto.BalanceRequest")
	proto.RegisterType((*BalanceRequest_Data)(nil), "vendorproto.BalanceRequest.Data")
	proto.RegisterType((*DataResponse)(nil), "vendorproto.DataResponse")
	proto.RegisterType((*DataResponse_Data)(nil), "vendorproto.DataResponse.Data")
	proto.RegisterType((*SimpleResponse)(nil), "vendorproto.SimpleResponse")
	proto.RegisterType((*SimpleResponse_Data)(nil), "vendorproto.SimpleResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0xf3, 0xe3, 0x36, 0x93, 0x38, 0xed, 0xd9, 0x53, 0x9d, 0xe3, 0xa6, 0xa8, 0x8a, 0x2c,
	0x40, 0x15, 0x17, 0x41, 0x0a, 0xdc, 0x70, 0x55, 0xb5, 0x29, 0x14, 0x2e, 0x2a, 0x55, 0xae, 0xe0,
	0x9a, 0xad, 0x77, 0xda, 0x1a, 0x12, 0x3b, 0x78, 0x37, 0x95, 0x72, 0xdf, 0xa7, 0xe1, 0x25, 0xe0,
	0x15, 0x78, 0x05, 0x9e, 0x04, 0xed, 0x4f, 0xc8, 0x6e, 0x48, 0x53, 0xa3, 0xf6, 0x2e, 0xf3, 0x79,
	0xf2, 0xed, 0x37, 0x3b, 0x3b, 0xdf, 0x40, 0xc0, 0xb1, 0xb8, 0x4e, 0x13, 0xec, 0x8d, 0x8b, 0x5c,
	0xe4, 0xa4, 0x79, 0x8d, 0x19, 0xcb, 0x0b, 0x15, 0x44, 0x4f, 0x20, 0x88, 0xf1, 0xcb, 0x04, 0xb9,
	0x78, 0x8b, 0x94, 0x61, 0x41, 0xb6, 0xa0, 0x2e, 0xf2, 0xcf, 0x98, 0x85, 0x5e, 0xd7, 0xdb, 0x6b,
	0xc4, 0x3a, 0x88, 0x6e, 0xaa, 0xd0, 0x32, 0x79, 0x6f, 0x52, 0x1c, 0x32, 0x42, 0xa0, 0x96, 0xe4,
	0x0c, 0x4d, 0x96, 0xfa, 0x2d, 0xb1, 0x8c, 0x8e, 0x30, 0xac, 0x68, 0x4c, 0xfe, 0x26, 0x5d, 0x68,
	0x32, 0xe4, 0x49, 0x91, 0x8e, 0x45, 0x9a, 0x67, 0x61, 0x55, 0x7d, 0xb2, 0x21, 0x12, 0x41, 0x2b,
	0xc9, 0x33, 0x41, 0x13, 0xf1, 0x7a, 0x44, 0xd3, 0x61, 0x58, 0x53, 0x29, 0x0e, 0x46, 0x1e, 0x43,
	0x60, 0xe2, 0x93, 0xfc, 0x3c, 0x1d, 0x62, 0x58, 0x57, 0x49, 0x2e, 0x68, 0x31, 0x9d, 0x5e, 0xe5,
	0x19, 0x86, 0xbe, 0xc3, 0xa4, 0x30, 0xc9, 0x44, 0x19, 0x2b, 0x90, 0xf3, 0x33, 0x51, 0x20, 0x8a,
	0x70, 0x4d, 0x33, 0x39, 0xa0, 0x54, 0x6d, 0x80, 0x41, 0x2a, 0xa6, 0xe1, 0xba, 0x56, 0x6d, 0x41,
	0x64, 0x0f, 0x36, 0x4c, 0x78, 0x9a, 0x73, 0x31, 0x90, 0x57, 0xd1, 0x50, 0x59, 0x8b, 0xb0, 0x54,
	0xf5, 0x9b, 0x9c, 0x0a, 0x0c, 0x41, 0xab, 0xb2, 0x31, 0xf2, 0x14, 0xda, 0x33, 0xf2, 0x7c, 0x92,
	0x89, 0x62, 0x1a, 0x36, 0x55, 0xd6, 0x02, 0x1a, 0x9d, 0x02, 0x1c, 0xa3, 0x30, 0x8d, 0x20, 0x7d,
	0xf0, 0xaf, 0x54, 0xd3, 0x54, 0x17, 0x9a, 0xfd, 0x4e, 0xcf, 0xea, 0x6c, 0xcf, 0x69, 0x6b, 0x6c,
	0x32, 0x49, 0x1b, 0x2a, 0x29, 0x53, 0x1d, 0xaa, 0xc7, 0x95, 0x94, 0x45, 0x02, 0x82, 0x41, 0x81,
	0x54, 0xe0, 0x7d, 0x48, 0x9f, 0x43, 0xfd, 0x42, 0xbe, 0x0a, 0xc5, 0xdb, 0xec, 0x6f, 0x2f, 0xfb,
	0x8b, 0x7a, 0x36, 0xb1, 0xce, 0x8b, 0x6e, 0x3c, 0x08, 0xde, 0x8f, 0xd9, 0x3d, 0x8f, 0x5d, 0xa8,
	0x65, 0x2e, 0xa3, 0x5a, 0x52, 0xc6, 0x25, 0x04, 0x07, 0x89, 0x7c, 0x84, 0x0f, 0xa9, 0x62, 0x36,
	0x05, 0xd5, 0xf9, 0x14, 0x44, 0x5f, 0x3d, 0x68, 0x1f, 0xd2, 0x21, 0xcd, 0x92, 0x07, 0x2d, 0xf8,
	0x25, 0xd4, 0x18, 0x15, 0xd4, 0xd4, 0xdb, 0x75, 0x18, 0xdc, 0xe3, 0x7a, 0x47, 0x54, 0xd0, 0x58,
	0x65, 0x77, 0x76, 0xa1, 0x26, 0x23, 0xf2, 0x1f, 0xf8, 0x74, 0x24, 0x1f, 0x96, 0x52, 0xe0, 0xc5,
	0x26, 0x8a, 0xbe, 0xf9, 0xd0, 0x52, 0xe9, 0xc8, 0xc7, 0x79, 0xc6, 0x91, 0xec, 0x02, 0x70, 0x41,
	0xc5, 0x84, 0x0f, 0x66, 0x13, 0x5f, 0x8f, 0x2d, 0x84, 0x84, 0xb0, 0x36, 0x42, 0xce, 0xe9, 0xe5,
	0x6c, 0xf4, 0x67, 0x21, 0xe9, 0x3b, 0x02, 0x77, 0x1d, 0x81, 0xf6, 0x11, 0xb6, 0xbc, 0xef, 0x75,
	0xa3, 0x4f, 0x57, 0xab, 0x0d, 0xc6, 0xbe, 0x58, 0xdb, 0x5e, 0x66, 0x36, 0x54, 0xb5, 0x6c, 0x68,
	0xc1, 0x72, 0x6a, 0x77, 0x5b, 0x4e, 0xbd, 0x8c, 0xe5, 0xf8, 0x65, 0x2c, 0x67, 0xad, 0x8c, 0xe5,
	0xac, 0x97, 0xb0, 0x9c, 0x46, 0x29, 0xcb, 0x81, 0x72, 0x96, 0xd3, 0x2c, 0x65, 0x39, 0xad, 0x65,
	0x96, 0x43, 0xfa, 0xb0, 0xc5, 0x52, 0x3e, 0x1e, 0xd2, 0xa9, 0x79, 0x51, 0x07, 0xfa, 0xcd, 0x04,
	0x2a, 0x7b, 0xe9, 0x37, 0x59, 0xf1, 0xb9, 0x93, 0xdc, 0x56, 0x0f, 0xcc, 0x05, 0x65, 0xc5, 0x89,
	0xb2, 0x1e, 0x76, 0x24, 0x45, 0x6e, 0xe8, 0x8a, 0x2d, 0x88, 0x3c, 0x82, 0x86, 0x09, 0x0f, 0xa7,
	0xe1, 0xa6, 0xfa, 0x3e, 0x07, 0xc8, 0x33, 0xd8, 0x1c, 0x52, 0x2e, 0x4e, 0x72, 0x96, 0x5e, 0xa4,
	0x86, 0xe4, 0x1f, 0x95, 0xf4, 0x07, 0x2e, 0xab, 0xb5, 0xb1, 0xc3, 0x69, 0x48, 0x74, 0xb5, 0x2e,
	0x2a, 0x35, 0x15, 0x98, 0xe4, 0x05, 0xd3, 0x17, 0xf7, 0xaf, 0xd6, 0x64, 0x41, 0xf2, 0x6e, 0x0b,
	0xbc, 0xc0, 0x02, 0xb3, 0x44, 0xf1, 0x6c, 0x75, 0xbd, 0xbd, 0x6a, 0xec, 0x60, 0xd1, 0x4f, 0x0f,
	0xda, 0x67, 0xe9, 0x68, 0x3c, 0xc4, 0x07, 0x98, 0xa1, 0x55, 0x43, 0xee, 0x1e, 0x62, 0x4f, 0xd1,
	0x47, 0x33, 0x44, 0xb7, 0xb5, 0xcf, 0xfb, 0x9b, 0xf6, 0x55, 0x96, 0xb4, 0xaf, 0xff, 0xa3, 0x02,
	0xfe, 0x07, 0xa5, 0x85, 0xec, 0x83, 0xaf, 0x97, 0x08, 0x71, 0x5d, 0xcc, 0xd9, 0x2c, 0x9d, 0xed,
	0x5b, 0xc7, 0x9f, 0xbc, 0x82, 0xea, 0x31, 0x0a, 0xf2, 0xbf, 0x93, 0x31, 0xdf, 0x74, 0xab, 0xfe,
	0xba, 0x0f, 0xbe, 0xde, 0x24, 0x0b, 0x67, 0x3b, 0xeb, 0xe5, 0x0e, 0x02, 0xbd, 0x04, 0x16, 0x08,
	0x9c, 0xcd, 0xb0, 0x8a, 0xe0, 0x1d, 0x04, 0x07, 0xec, 0xd3, 0x84, 0x0b, 0x73, 0x8b, 0x64, 0x67,
	0x85, 0x11, 0x77, 0x76, 0x56, 0x34, 0xf0, 0xdc, 0x57, 0xe8, 0x8b, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x2f, 0x9e, 0xe3, 0xb2, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VendorClient is the client API for Vendor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VendorClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error)
	AdjustBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type vendorClient struct {
	cc *grpc.ClientConn
}

func NewVendorClient(cc *grpc.ClientConn) VendorClient {
	return &vendorClient{cc}
}

func (c *vendorClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/vendorproto.Vendor/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/vendorproto.Vendor/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/vendorproto.Vendor/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/vendorproto.Vendor/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorClient) AdjustBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/vendorproto.Vendor/AdjustBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorServer is the server API for Vendor service.
type VendorServer interface {
	Create(context.Context, *CreateRequest) (*DataResponse, error)
	Get(context.Context, *GetRequest) (*DataResponse, error)
	Update(context.Context, *UpdateRequest) (*DataResponse, error)
	Action(context.Context, *ActionRequest) (*DataResponse, error)
	AdjustBalance(context.Context, *BalanceRequest) (*SimpleResponse, error)
}

// UnimplementedVendorServer can be embedded to have forward compatible implementations.
type UnimplementedVendorServer struct {
}

func (*UnimplementedVendorServer) Create(ctx context.Context, req *CreateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedVendorServer) Get(ctx context.Context, req *GetRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedVendorServer) Update(ctx context.Context, req *UpdateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedVendorServer) Action(ctx context.Context, req *ActionRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}
func (*UnimplementedVendorServer) AdjustBalance(ctx context.Context, req *BalanceRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustBalance not implemented")
}

func RegisterVendorServer(s *grpc.Server, srv VendorServer) {
	s.RegisterService(&_Vendor_serviceDesc, srv)
}

func _Vendor_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendorproto.Vendor/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendor_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendorproto.Vendor/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendor_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendorproto.Vendor/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendor_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendorproto.Vendor/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendor_AdjustBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).AdjustBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendorproto.Vendor/AdjustBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).AdjustBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vendor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vendorproto.Vendor",
	HandlerType: (*VendorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Vendor_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Vendor_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Vendor_Update_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Vendor_Action_Handler,
		},
		{
			MethodName: "AdjustBalance",
			Handler:    _Vendor_AdjustBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
